# Configuracion del Token Server Server

spring:
   application:
       name: TKNSSERV
   
server:
   # Puerto del servicio
   port: 8090

---
spring:
   profiles: dev
   application:
      name: demoservice
server:
   port: 9090

---
spring: 
   profiles: prod
   application:
      name: demoservice
server: 
   port: 4431